spring:
    datasource:
         url: jdbc:postgresql://localhost:5432/booting
         username: postgres
         password: 1234

    jpa:
       hibernate:
          ddl-auto: create
       show-sql: true

server:
 port: 8080

